---
- hosts: localhost
  vars:
    region: us-east-1
  tasks: 
  - name: Detach volume from instance {{ ec2.instances[0]['instance_id'] }}
    amazon.aws.ec2_vol:
      id: "{{ vol2 }}"
      instance: None
      instance: "{{ ec2.instances[0]['instance_id'] }}"
      region: "{{ region }}"
        
  - name: "{{'Default RHEL 8 Image with partitions defined' | upper}}"
    amazon.aws.ec2_ami:
      delete_snapshot: true
      description: This image will be used as a template for RHEL 8 builds
      instance_id: "{{ ins_id }}"
      name: 'RHEL9_IMAGE_WITH_PARTITIONS_DEFINED'
      region: "{{ region }}"
      tags: { 
      Name: 'RHEL8 GOLD IMAGE WITH DEFINED PARTIIIONS',
      OS_Type: 'Linux',
      Role: 'GOLDIMAGE',
      POC: Sylvester.Sevalie@usdoj.gov
      }
      wait: true
      
    
      
      
      
      
    
