---
- hosts: localhost
  vars:
    region: us-east-1
  tasks: 
  - name: 'Default RHEL 8 Image with partitions defined' | upper
    amazon.aws.ec2_ami:
      delete_snapshot: true
      description: This image will be used as a template for RHEL 8 builds
      instance_id: 
    
