- hosts: all 
  become: true
  tasks: 
  - name: copy profile file to root home 
    copy: 
      src: bash_profile
      dest: /root/.bash_profile
      mode: 0600
      owner: root
      group: root