---
- hosts: localhost
  tasks: 
    - name: Get EC2 Instance info by tag
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Role": GoldImageTemplate
          instance-state-name: running
        region: "{{ region }}"
      register: ec2
      
    - ansible.builtin.debug:
       msg: "{{ ec2 }}"
       
    - name: Create a snapshot from instance block device /dev/sda1
      amazon.aws.ec2_snapshot:
        description: GoldImageTemplateSnapshot
        region: "{{ region }}"
        volume_id: "{{ ec2.instances[0]['block_device_mappings'][0]['ebs']['volume_id'] }}"
        snapshot_tags:
          Name: GoldImageTemplateSnapshot
      register: gits

    - name: Create volume from above snapshot and attach to instance
      amazon.aws.ec2_vol:
         instance: "{{ ec2.instances[0]['instance_id'] }}"
         tags:
           Name: GoldImageTemplateVol
         snapshot: "{{ gits['snapshot_id'] }}"
         region: "{{ region }}"
         volume_type: gp2
         #iops: '100'
         device_name: /dev/sdc
      register: sdc
    #delegate_to: localhost
