---
- hosts: localhost
  connection: local
  tasks:
  - block:
    - name: Get info about instance
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Role": GoldImageTemplate
          instance-state-name: running
      register: ec2

    - name: Get volumes Id
      ansible.builtin.set_fact:
        vol1: "{{ ec2['instances'][0]['block_device_mappings'][0]['ebs']['volume_id'] }}"
        vol2: "{{ ec2['instances'][0]['block_device_mappings'][2]['ebs']['volume_id'] }}"

    - ansible.builtin.debug:
       msg: "Here are the two volume ids {{ vol1 }}, {{ vol1 }}"

    - name: stop the instance
      amazon.aws.ec2_instance:
        instance_ids:  "{{ ec2.instances[0]['instance_id'] }}"
        state: stopped
        region: "{{ region }}"
        wait: True

    - name: Detach volume from instance {{ ec2.instances[0]['instance_id'] }}
      amazon.aws.ec2_vol:
        id: "{{ item }}"
        #instance: None
        instance: "{{ ec2.instances[0]['instance_id'] }}"
        region: "{{ region }}"
      loop:
       - "{{ vol1 }}"
       - "{{ vol2 }}"

    - name: Attach {{ vol2 }} to {{ ec2.instances[0]['instance_id'] }} as /dev/sda1
      amazon.aws.ec2_vol:
       instance: "{{ ec2.instances[0]['instance_id'] }}"
       id: "{{ vol2 }}"
       region: "{{ region }}"
       device_name: /dev/sda1
       delete_on_termination: yes

    - name: Start the instance
      amazon.aws.ec2_instance:
        instance_ids:  "{{ ec2.instances[0]['instance_id'] }}"
        state: running
        region: "{{ region }}"
        wait: True
    delegate_to: localhost

  - name: this is just to pass on the instance ID to the next template.
    set_stats:
      data:
        ins_id: "{{ ec2.instances[0]['instance_id'] }}"

