---
- name: Is ssh listening on 7741?
  hosts: all
  become: true
  gather_facts: false
  tasks: 
    - name: Check for Ansible port {{ ansible_port }}
      wait_for: 
        port: "{{ ansible_port }}"
        host: "{{ inventory_hostname }}"
        state: started
        connection_timeout: "5"
        timeout: "5"
      delegate_to: localhost
      ignore_errors: true
      register: ssh_port
    
    - debug: 
        msg: "{{ ssh_port }}"

    - name: Is ssh on default port? 
      wait_for: 
        port: "22"
        host: "{{ inventory_hostname }}"
        state: started
        connection_timeout: "5"
        timeout: "5"
      delegate_to: localhost
      ignore_errors: true
      register: ssh_default_port
      when: 
        - ssh_port.state is undefined


