---
- hosts: all
  become: false
  gather_facts: false
  tasks: 
    - block: 
        - name: Check for Ansible port {{ non_default_ssh_port }}
          wait_for: 
            port: "{{ none_default_ssh_port }}"
            host: "{{ inventory_hostname }}"
            state: started
            connect_timeout: "5"
            timeout: "5"
          delegate_to: localhost
      
      rescue:
        - name: Is ssh listening on default port? 
          wait_for: 
            port: "{{ non_default_ssh_port }}"
            host: "{{ inventory_hostname }}"
            state: started
            connect_timeout: "5"
            timeout: "5"
          delegate_to: localhost
        
        - name: Create a list of failed nodes
          shell: echo {{ inventory_hostname }} failed port test >> /tmp/default_ssh.txt
          delegate_to: controller
          vars: 
            - ansible_port: "{{ default_ssh_port }}"
        
        - name: Change ssh port from 22 to 7741
          lineinfile: 
            path: "{{ item }}"
            regexp: '^#[\s]?Port.*$'
            line: Port 22
          loop: "{{ ssh_config_path }}"
          become: true
          vars: 
            - ansible_port: "{{ non_default_ssh_port }}"

        - name: Restart sshd service 
          service: name=sshd state=restarted enabled=true

