---
- name: Is ssh listening on 7741?
  hosts: all
  become: false
  gather_facts: false
  tasks: 
    - block: 
        - name: Check for Ansible port {{ ssh_port }}
          wait_for: 
            port: "{{ ssh_port }}"
            host: "{{ inventory_hostname }}"
            state: started
            connect_timeout: "5"
            timeout: "5"
          delegate_to: localhost
          register: port
      
      rescue:
        - name: Is ssh listening on default port? 
          wait_for: 
            port: "22"
            host: "{{ inventory_hostname }}"
            state: started
            connect_timeout: "5"
            timeout: "5"
          delegate_to: localhost
          
        - name: Create a spreadsheet of failed nodes
          shell: echo {{ inventory_hostname }} failed port test >> /tmp/default_ssh.txt
          delegate_to: controller
          vars: 
            - ansible_port: 22


