---
- hosts: localhost
  vars:
    region: "us-east-1"
  tasks:
  - name: check instance state
    amazon.aws.ec2_instance_info:
      region: us-east-1
      filters:
        "tag:Role": "GoldImageTemplate"
        "tag:OS_Type": "Linux"
    register: instance_state
    
     # - debug:
     #    var: instance_state.instances[0]['instance_id']
    
  - name: stop instance conditionally
    amazon.aws.ec2_instance:
      instance_ids: "{{ instance_state.instances[0]['instance_id'] }}"
      region: us-east-1
      state: stopped
    when: instance_state.instances[0]['state']['name'] == 'running'
    tags: stopped
    
  - name: start the instance if stopped
    amazon.aws.ec2_instance:
      region: us-east-1
      instance_ids: "{{ instance_state.instances[0]['instance_id'] }}"
      state: started
    when: instance_state.instances[0]['state']['name'] == 'stopped'
    tags: running
