---
- hosts: localhost
  vars:
    region: "us-east-1"
    ids: ['i-00051e115e3ca8063']
  tasks:
  - name: check current state of the instance  
    amazon.aws.ec2_instance_info:
       instance_ids: "{{ ids }}"
       region: "{{ region }}"
         #   filters:
         #instance-state-name: running
    register: instance_state

#  - debug:
#      var: instance_state.instances[0]['state']

  - name: stop instance conditionally
    amazon.aws.ec2_instance:
      instance_ids: "{{ ids }}"
      region: "{{ region }}"
      state: stopped
    when: instance_state.instances[0]['state']['name'] == 'running'

  - name: start the instance if stopped
    amazon.aws.ec2_instance:
      region: "{{ region }}"
      instance_ids: "{{ ids }}"
      state: started
    when: instance_state.instances[0]['state']['name'] == 'stopped'
